theme: jekyll-theme-minimal
title: Claroline Connect
description: Learning management system
logo: images/logo.png
show_downloads: true
version: 11.2.21 # TODO retrieve it

collections:
  nav:
    output: true
